# Office Models - Full office management system
from app.models.office.office_models import (
    Department,
    Employee,
    Location,
    MeetingRoom,
    Resource,
    RoomBooking,
    ResourceBooking,
    Customer,
    CustomerContact,
    Appointment,
    TimeEntry,
    Attendance,
    BookingStatus,
    AppointmentStatus,
    PortalTask,
    Document,
    Project,
    TaskStatus,
    TaskPriority,
    ProjectStatus,
    DocumentCategory,
)

__all__ = [
    "Department",
    "Employee",
    "Location",
    "MeetingRoom",
    "Resource",
    "RoomBooking",
    "ResourceBooking",
    "Customer",
    "CustomerContact",
    "Appointment",
    "TimeEntry",
    "Attendance",
    "BookingStatus",
    "AppointmentStatus",
    "Task",
    "Document",
    "Project",
    "TaskStatus",
    "TaskPriority",
    "ProjectStatus",
    "DocumentCategory",
]
